(*
NOME: FB_INFO
DESCRIÇÃO: ANTIGO IHM_INFO CONTEM AS PRINCIPAIS INFORMAÇOES DA IHM COMO POR EXEMPLO DATA E HORA CONVERTENDO-AS EM STRING  E AS PREPARANDO PARA IMPRESSÃO



20210107 - ADICIONA 1 A S_PD
20201208 - ANULA NOP02 EM CASO DE NOP_2 = 0
20201124 - RESETA PRODUÇÃO EM CASO DE TROCA DE OP
*)
IF IN THEN

	// ELIMINA CORTE DE ZEROS NA VARIAVEL NOP02
	IF NOP_2 < 1 THEN
		NOP02 := '';
	ELSIF NOP_2 < 10 THEN
		NOP02 := '000' + ANY_TO_STRING(NOP_2);
	ELSIF NOP_2 < 100 THEN
		NOP02 := '00' + ANY_TO_STRING(NOP_2);
	ELSIF NOP_2 < 1000 THEN
		NOP02 := '0' + ANY_TO_STRING(NOP_2);
	ELSIF NOP_2 >= 1000 THEN
		NOP02 := ANY_TO_STRING(NOP_2);
	END_IF;
	
	// GERA STRING COM DADOS DE DATA E HORA
	S_DT := ANY_TO_STRING(DT_DD) + '/' + ANY_TO_STRING(DT_MM) + '/' + RIGHT(ANY_TO_STRING(DT_YYYY),2) + ' ' + ANY_TO_STRING(TM_HH) + ':' + ANY_TO_STRING(TM_MM) + ':' + ANY_TO_STRING(TM_SS);
	
	// GERA STRING CRACHA OPERADOR
	S_ID := ANY_TO_STRING(INT_ID);

	// GERA STRING PRODUÇÃO ATUAL
	S_PD := ANY_TO_STRING(PD_AT + 1);

	// GERA STRING COM O NUMERO DA OP
	S_OP := ANY_TO_STRING(NOP_1) + NOP02;
	
	// RESETA PRODUÇÃO EM CASO DE TROCA DE OP
	TON_1(PD_RS,T#500MS);
	
	IF S_OP <> STR_NW THEN
		PD_RS := TRUE;
		STR_NW := S_OP;
	END_IF;
	
	IF TON_1.Q THEN
		PD_RS := FALSE;
	END_IF;	
	
	// NOMERO DA ORDEM DE PRODUÇÃO
	IF NOP_1 > 0 THEN
		ORP_OK := TRUE;
	ELSE 
		ORP_OK := FALSE;
	END_IF;

	// OPERADOR
	IF INT_ID > 0 THEN
		CRACHA_OK := TRUE;
	ELSE
		CRACHA_OK := FALSE;
	END_IF;

	// MODELO
	IF MD > 0 THEN
		MOD_OK := TRUE;
	ELSE 
		MOD_OK := FALSE;
	END_IF;
	
	// PRODUÇÃO ALVO
	IF PD_AV > 0 AND PD_AV > PD_AT THEN
		PROD_OK := TRUE;
	ELSE 
		PROD_OK := FALSE;
	END_IF;
	
	// ORDEM DE PRODUÇÃO
	IF ORP_OK AND CRACHA_OK AND MOD_OK AND PROD_OK THEN
		Q := IN;
	ELSE 
		Q := FALSE;
	END_IF;

END_IF;
